# Generated by Django 2.0.7 on 2018-08-04 14:09

import PersonalDataApi.datapoints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='category',
            field=models.TextField(choices=[(PersonalDataApi.datapoints.models.CategoryTypes('TST'), 'TST'), (PersonalDataApi.datapoints.models.CategoryTypes('WGT'), 'WGT'), (PersonalDataApi.datapoints.models.CategoryTypes('SPC'), 'SPC'), (PersonalDataApi.datapoints.models.CategoryTypes('SHT'), 'SHT'), (PersonalDataApi.datapoints.models.CategoryTypes('FOD'), 'FOD'), (PersonalDataApi.datapoints.models.CategoryTypes('HRT'), 'HRT')], max_length=3),
        ),
    ]
