# Generated by Django 2.0.7 on 2018-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0002_auto_20180804_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
