# Generated by Django 2.1 on 2018-08-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0003_auto_20180804_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='category',
            field=models.TextField(choices=[('CategoryTypes.test', 'TST'), ('CategoryTypes.weight', 'WGT'), ('CategoryTypes.speech_audio', 'SPC'), ('CategoryTypes.shit_cam', 'SHT'), ('CategoryTypes.food_picture', 'FOD'), ('CategoryTypes.heart_rate', 'HRT')], max_length=3),
        ),
    ]
