# Generated by Django 2.1 on 2018-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0004_auto_20180807_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='category',
            field=models.TextField(choices=[('TST', 'test'), ('WGT', 'weight'), ('SPC', 'speech_audio'), ('SHT', 'shit_cam'), ('FOD', 'food_picture'), ('HRT', 'heart_rate')], max_length=3),
        ),
    ]
