# Generated by Django 2.1 on 2018-08-06 16:10

import PersonalDataApi.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('language', models.TextField(choices=[(PersonalDataApi.profiles.models.Languages('en-US'), 'en-US'), (PersonalDataApi.profiles.models.Languages('da-DK'), 'da-DK')], max_length=5)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='profilepictures')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
