# Generated by Django 2.1 on 2018-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
